### PR TITLE
Added a translateable AppData file for Linux software galleries

### PR DESCRIPTION
**Pull request by Mailaender**
See https://en.opensuse.org/openSUSE:AppStore for details.

### CODE REVIEW

**Comment by Mailaender** [comment]
See https://build.opensuse.org/request/show/454765 for an integration test.

**Comment by Alexey-Yakovenko** [comment]
Please answer all of the questions below:

* What is this file?
* What does it fix?
* How can I test that it works?
* Why do you think it's useful to have this file in Deadbeef source code repository?
* Where is it used?

**Comment by Alexey-Yakovenko** [comment]
It looks like this file adds certain metadata for one of the linux distribution package repositories.

It's not something that I consider as a good thing to have in deadbeef source code.

**Comment by Mailaender** [comment]
The idea of the AppData project is that the developer shall be in control. For Fedora this is mandatory. For @openSUSE it just adds a pretty entry with a screenshot to https://software.opensuse.org/appstore and tools which aggregate it.

**Comment by Alexey-Yakovenko** [comment]
In control of what?

**Comment by Mailaender** [comment]
@hughsie had a nice explanation at https://people.freedesktop.org/~hughsient/appdata/ that I used to link, but now it just redirects to the AppStream definition which isn't exactly what this is about.

**Pull request closed without merging**
