### PR TITLE
add option to start in tray: tray.start_minimized

### PR DESCRIPTION
**Pull request by mitchnull**
partial fix for issues #618 and #521

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
I think that the configuration variable name is wrong, because:

1. It doesn't have anything to do with the tray / notification area.
2. It doesn't start the player minimized. In fact, it doesn't even start it hidden. Instead, it hides the window after it's been shown.

However, if we just keep the window hidden, i.e. not call gtk_widget_show (mainwin) -- this might cause all sorts of problems as well..

So at the very least, it needs to be called "gtkui.start_hidden".

Then, this needs a QA pass. We need to make sure that the following still works:

* the saved layout is correctly restored on startup
* columns have correct sizes in "column autoresize" mode

**Comment by mitchnull** [comment]
Agreed... 

In fact, despite my initial tests working, now I get IA__gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed errors all over the place...

Please disregard this patch, I'll try to find a more reliable way...

**Comment by mitchnull** [comment]
Changed the option name and used g_idle_add() to avoid the GTK assertions.  Seems to be working fine now.

**Comment by oleksiy-unity3d** [comment]
Right, using g_idle_add should make sure that gtk_widget_hide will be called after all of the initial things taking place (like configure/realize), so there's a chance that layout and column sizes will be initialized correctly now.

**Comment by Alexey-Yakovenko** [comment]
Right, using g_idle_add should make sure that gtk_widget_hide will be called after all of the initial things taking place (like configure/realize), so there's a chance that layout and column sizes will be initialized correctly now.

**Pull request merged**
