### PR TITLE
gtkui: playqueue removal on context menu, fix for #1335

### LINKED ISSUE #1335: Playlist context menu with range selection doesn't always activate "Remove from Playback Queue"
If more than one playlist item is selected and one of them is in the playback queue, then the context menu should allow "Remove from Playback Queue" to be performed.  It is only allowed if the actual item under the pointer when clicked is in the playqueue.

### PR DESCRIPTION
**Pull request by Lithopsian**
This fixes #1335 by activating the context menu item if any of the selected playlist items are in the playqueue.

The diff is showing previous commits in addition to this one.  Is this from the manual merge you did?

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
strange.. I remember merging this PR (manually), but now it's updated again with a new commit...

**Comment by Lithopsian** [comment]
This is a new PR for commit 438812f, but for some reason it also shows the commits from the previous PR.  I see your manual merge for the previous PR, so you definitely did it.

**Comment by Alexey-Yakovenko** [comment]
merged

**Comment by Alexey-Yakovenko** [comment]
@Lithopsian 
please fix the email address in the git configuration, unless you use an invalid one intentionally.

**Pull request closed without merging**
