### PR TITLE
Create help.zh_TW.txt

### PR DESCRIPTION
**Pull request by laichiaheng**

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
so will you update this PR?

**Comment by laichiaheng** [comment]
What does PR mean?

**Comment by Alexey-Yakovenko** [comment]
**P**ull **R**equest

**Comment by Alexey-Yakovenko** [comment]
@laichiaheng so are you going to update this pull request with the fixed text? I don't mind merging it -- I can't read chinese anyway -- but you said it contains an error or what?

**Comment by laichiaheng** [comment]
Yes, I type a wrong word.

**Pull request merged**
