### PR TITLE
pltbrowser: add inline editing and F2 shortcut to edit playlist name

### PR DESCRIPTION
**Pull request by cboxdoerfer**

### CODE REVIEW

**Comment by cboxdoerfer** [comment]
Build on drone.io fails with this patch. I'll reopen when I have solved that.

**Comment by Alexey-Yakovenko** [comment]
You can simply update the pull request.

**Comment by cboxdoerfer** [comment]
yeah, but at that time I only saw "build failed" and just wanted to be sure you don't pull some mature breakage. Turned out there was just some incompatiblity with the gtk2 version in the static deps.

**Comment by Alexey-Yakovenko** [comment]
I remember, that "event-after" handler was made on purpose, for correctly handling the context menu activation on right click (the case where you hold the mouse button, select the menu item, and then release the button), and the change you made wouldn't work correctly, or maybe break something else. Why did you change this?

**Comment by Alexey-Yakovenko** [comment]
Yeah, I should've written a comment about why it was done this way. But try to play with context menu, and you'll see for yourself.

**Comment by cboxdoerfer** [comment]
Oh, I just saw that this event was fired quite often and thought button-press-event is enough. Of course I"ll change it back.

**Pull request merged**
