### PR TITLE
tf: Implement $num(n,len) (fixes #1279)

### LINKED ISSUE #1279: [tf 2.0] Support for $num() fb2k string function
waker, during a short chat with one of your main developers, he too said this function is not just another gimmick, but a valuable addition to TF 2.0.

Let me requote the most important bit from fb2k docs:

`num(n,len)`

Formats the integer number n in decimal notation with len characters.(...) If n is not numeric, it is treated as zero. Examples:

    $num(123,5) → 00123
    $num(-123,5) → -0123
    $num(4.8,5) → 00004
    $num(A1,5) → 00000

Basic idea: there is neither a rounding function in ddb nor in fb2k. So back in my Win2k days, I've simply "misused" this function to turn a '123.47' value (think of BPM!) into a better readable '123'.

I can't deny, that there is lots of __room for improvement towards fb2k__. So deadbeef might, in theory, go ahead and offer a `$num(n, len, digits)` variant that would even allow a `digits` amount of digits (fixed).
That would turn a pretty silly, overexact BPM value of 123.874 into '123.8'.
Equivalent functions in other languages will be `trunc()` or, IIRC from my 80s BASIC days, `FIX()`. :)

Thanks for considering in advance.

### PR DESCRIPTION
**Pull request by Serranya**
I hope everything is alright. I am no professional c developer.

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
malloc, free are unacceptable.

snprintf is.. undesirable :)

**Comment by Serranya** [comment]
So should I use arrays instead of malloc/free ?

And maybe manually pad the number string instead of using snprintf ? Or just a different function I dont know yet ?

**Comment by Alexey-Yakovenko** [comment]
Please see e.g. how the `$hex` is implemented -- it does a very similar thing.

**Comment by Serranya** [comment]
I got rid of the snprintf and dynamic memory allocation.

I would appreciate another review from you.

**Pull request merged**
