### PR TITLE
Update deadbeef.desktop.in

### PR DESCRIPTION
**Pull request by laichiaheng**
Add some Chinese keywords.

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
Some explanation is needed about what this change fixes or adds.

**Comment by laichiaheng** [comment]
Add the Chinese keywords for searching this app on menu.

**Comment by Alexey-Yakovenko** [comment]
Putting multiple localisations in one huge line doesn't seem to scale well in the long run.

Is there anything like Keywords[LANGUAGE_CODE] syntax, same as for other entries in the desktop file?

**Comment by laichiaheng** [comment]
Done.

**Comment by laichiaheng** [comment]
Complete

**Comment by Alexey-Yakovenko** [comment]
Hmm.. Do you still have to duplicate english in every localisation?
I would expect that english is included automatically..

Btw, is there any way for me to test how this works?

I mean, what's the use case for that, which DE supports it, etc?

**Comment by laichiaheng** [comment]
I'm using Unity desktop, I edit "/usr/share/applications/deadbeef.desktop" to the last one I posted, and it works for me, and the English still needs to be added for other languages.

**Comment by Alexey-Yakovenko** [comment]
ok, I got it. will merge later (need to collapse the commits, so can't do it via github interface)

**Pull request closed without merging**
