### PR TITLE
Statusnotifier fixes

### PR DESCRIPTION
**Pull request by ugilio**
(Continuation from #1246)
In this PR:
 * Avoid the use of new api gdk_pixbuf_get_byte_length and g_variant_new_fixed_array
 * Add status notifier plugin to scripts

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
This PR can't be merged. You first need to pull origin/master, and apply your new fix on top.
I'll try to appy the last fix individually.

**Comment by Alexey-Yakovenko** [comment]
Sorry, I meant that you need to pull origin/statusnotifier. It didn't land on master yet.

**Comment by ugilio** [comment]
I deleted my statusnotifier branch and re-created from your statusnotifier branch but it still says the PR cannot be automatically merged.

I'm attaching here the two patches so you can apply them

```
commit 7f6e35ce7b0dde8f2238966e320b978d9b3148a7
Author: Giulio Bernardi <ugilio@users.noreply.github.com>
Date:   Sat Aug 15 14:20:29 2015 +0200

    Avoid to use functions that appeared in new libraries
    
    Avoid gdk_pixbuf_get_byte_length and g_variant_new_fixed_array

diff --git a/plugins/statusnotifier/statusnotifier.c b/plugins/statusnotifier/statusnotifier.c
index 1d6e608..1b427ca 100644
--- a/plugins/statusnotifier/statusnotifier.c
+++ b/plugins/statusnotifier/statusnotifier.c
@@ -198,7 +198,7 @@ static void sn_seticondata(IconData **data, GdkPixbuf* pixbuf) {
     IconData *id = g_malloc(sizeof(IconData));
     id->w = gdk_pixbuf_get_width(pixbuf);
     id->h = gdk_pixbuf_get_height(pixbuf);
-    id->len = gdk_pixbuf_get_byte_length(pixbuf);
+    id->len = rowstride*id->h;
     if (rowstride > (id->w * 4))
         sn_get_pixel_rowstride(id, pixbuf, rowstride);
     else
@@ -546,8 +546,8 @@ static GVariant* icondata_to_variant(IconData* id) {
     GVariantBuilder *bld;
     bld = g_variant_builder_new(G_VARIANT_TYPE("a(iiay)"));
     if (id) {
-        GVariant *pixdata = g_variant_new_fixed_array(G_VARIANT_TYPE_BYTE,
-                id->pixdata, id->len, 1);
+        GVariant *pixdata = g_variant_new_from_data(G_VARIANT_TYPE("ay"),
+                id->pixdata, id->len, TRUE, NULL, NULL);
         g_variant_builder_add(bld, "(ii@ay)", id->w, id->h, pixdata);
     }
     ret = g_variant_new("a(iiay)", bld);
```

```
commit 591e062709b29dbcbb6eac41436d79e7e80fae3f
Author: Giulio Bernardi <ugilio@users.noreply.github.com>
Date:   Sat Aug 15 14:22:23 2015 +0200

    Update scripts to handle statusnotifier plugin

diff --git a/scripts/configure_minimal.sh b/scripts/configure_minimal.sh
index 4044a03..24100a0 100755
--- a/scripts/configure_minimal.sh
+++ b/scripts/configure_minimal.sh
@@ -1 +1 @@
-./configure --enable-maintainer-mode --disable-nullout --disable-oss --disable-sid --disable-ffap --disable-vtx --disable-adplug --disable-vorbis --disable-ffmpeg --disable-flac --disable-sndfile  --disable-wavpack --disable-cdda --disable-gme --disable-dumb --disable-musepack --disable-wildmidi --disable-tta --disable-dca --disable-aac --disable-mms --disable-shn --disable-ao --disable-supereq --disable-artwork --disable-lfm --disable-vfs-curl --disable-hotkeys --disable-notify --disable-shellexec
+./configure --enable-maintainer-mode --disable-nullout --disable-oss --disable-sid --disable-ffap --disable-vtx --disable-adplug --disable-vorbis --disable-ffmpeg --disable-flac --disable-sndfile  --disable-wavpack --disable-cdda --disable-gme --disable-dumb --disable-musepack --disable-wildmidi --disable-tta --disable-dca --disable-aac --disable-mms --disable-shn --disable-ao --disable-supereq --disable-artwork --disable-lfm --disable-vfs-curl --disable-hotkeys --disable-notify --disable-shellexec --disable-statusnotifier
diff --git a/scripts/portable_package_static.sh b/scripts/portable_package_static.sh
index 08ced9a..542afd7 100755
--- a/scripts/portable_package_static.sh
+++ b/scripts/portable_package_static.sh
@@ -80,6 +80,7 @@ tar jcvf ../../portable_out/build/$OUTNAME\
     $PLUGDIR/pltbrowser_gtk2.so\
     $PLUGDIR/pltbrowser_gtk3.so\
     $PLUGDIR/in_sc68.so\
+    $PLUGDIR/statusnotifier.so\
     $PLUGDIR/data68\
     $PIXMAPDIR\
     $SRCDIR/locale\
diff --git a/scripts/portable_postbuild.sh b/scripts/portable_postbuild.sh
index 11f5dbd..695d1af 100755
--- a/scripts/portable_postbuild.sh
+++ b/scripts/portable_postbuild.sh
@@ -41,7 +41,8 @@ for i in nullout cdda flac alsa mp3 hotkeys vtx \
 	 lastfm sid adplug sndfile artwork alac \
 	 supereq gme dumb notify musepack wildmidi \
 	 tta dca aac mms shn ao shellexec vfs_zip \
-	 m3u converter pulse dsp_libsrc mono2stereo wma ; do
+	 m3u converter pulse dsp_libsrc mono2stereo \
+	 statusnotifier wma ; do
     if [ -f ./plugins/$i/.libs/$i.so ]; then
 		 cp ./plugins/$i/.libs/$i.so $PLUGDIR/
 	elif [ -f ./plugins/$i/$i.so ]; then
diff --git a/scripts/quickinstall.sh b/scripts/quickinstall.sh
index e8e2c11..8a811d6 100755
--- a/scripts/quickinstall.sh
+++ b/scripts/quickinstall.sh
@@ -54,3 +54,4 @@ cp ./plugins/pltbrowser/.libs/pltbrowser_gtk2.so $PREFIX/lib/deadbeef/
 cp ./plugins/pltbrowser/.libs/pltbrowser_gtk3.so $PREFIX/lib/deadbeef/
 cp ./plugins/coreaudio/.libs/coreaudio.so $PREFIX/lib/deadbeef/
 cp ./plugins/sc68/.libs/in_sc68.so $PREFIX/lib/deadbeef/
+cp ./plugins/statusnotifier/.libs/statusnotifier.so $PREFIX/lib/deadbeef/
```

**Comment by Alexey-Yakovenko** [comment]
I already applied them.

**Comment by ugilio** [comment]
With build 643 there is an empty icon, and in the terminal I see 
`(deadbeef:7669): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_file: assertion 'error == NULL || *error == NULL' failed`

I need to debug this a little bit

**Pull request closed without merging**
