### PR TITLE
process cue files internally / get rid of the cue playlist plugin

### PR DESCRIPTION
**Pull request by wdlkmpx**

### CODE REVIEW

**Comment by wdlkmpx** [comment]
the easy way to fix this would be:

- remove the code that automatically loads cue files with the same basename when opening audio files.

with that single change deadbeef will behave exactly like foobar, adding the "raw" cdimage + the cdimage split into tracks. but it won't that cool and automatic..

**Comment by Alexey-Yakovenko** [comment]
> remove the code that automatically loads cue files with the same basename when opening audio files.

There are following concerns about this.

1. Cuesheets often have wrong filenames. Most of the time WAV extension, but can be entirely different filename, and no way to map it. So it's still mandatory to find the audio file from cue basename, when opening cue file.

2. It's often useful to have 1 cue + multiple images of the same album in different formats, in the same folder. This is useful for testing.
Example:
```
Artist - Album.cue
Artist - Album.mp3
Artist - Album.ape
Artist - Album.flac
Artist - Album.ogg
```
Currently, I can load each of the audio files with the same cuesheet.
Some of the use cases can be solved by moving test files + the cue into separate folders to solve this use case..
In some cases it becomes more hassle though.

3. Many files have embedded cuesheets, which must be ignored when external ones are found, but there's a config option to prioritize them over the external ones. I'm not sure how to handle this.

4. To do what you suggested, we'd need to go through all input plugins, modify the code, etc.

So my take on this is to be able to detect that cue for this file was already added, and avoid doing it the 2nd time.

**Comment by Alexey-Yakovenko** [comment]
What do you think about the approach that I suggested in the other comment?

basically, when adding folders -- add each audio file which was cue-splitted into a list, and then ignore it if it attempts cue-splitting again?

**Comment by Alexey-Yakovenko** [comment]
(sorry, closed by accident)

**Comment by Alexey-Yakovenko** [comment]
followup to this:

> basically, when adding folders -- add each audio file which was cue-splitted into a list, and then ignore it if it attempts cue-splitting again?

the files need to be sorted, and *.cue processed first. I'll try to find the old comment. It probably has more details.

**Comment by Alexey-Yakovenko** [comment]
https://github.com/Alexey-Yakovenko/deadbeef/pull/1809#issuecomment-309477430

**Comment by wdlkmpx** [comment]
Yeah i'll try to figure out a way to implement that

**Comment by Alexey-Yakovenko** [comment]
@wdlkmpx FYI: your implementation doesn't support the case where there are for example 2 flac files (1.cue and 2.cue), and 1 cue file.

Example provided:

```
REM GENRE Soundtrack
REM DATE 1985
REM DISCID 7308F20A
PERFORMER "Various"
TITLE "Back To The Future"
FILE "1.flac" WAVE
  TRACK 01 AUDIO
    TITLE "The Power Of Love"
    PERFORMER "Huey Lewis And The News"
    INDEX 00 00:00:00
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Time Bomb Town"
    PERFORMER "Lindsey Buckingham"
    INDEX 00 03:58:00
    INDEX 01 03:58:00
  TRACK 03 AUDIO
    TITLE "Theme"
    PERFORMER "Back To The Future"
    INDEX 00 06:46:00
    INDEX 01 06:46:00
  TRACK 04 AUDIO
    TITLE "Heaven Is One Step Away"
    PERFORMER "Eric Clapton"
    INDEX 00 10:06:00
    INDEX 01 10:06:00
  TRACK 05 AUDIO
    TITLE "Back In Time"
    PERFORMER "Huey Lewis And The News"
    INDEX 00 14:19:00
    INDEX 01 14:19:00
FILE "2.flac" WAVE
  TRACK 06 AUDIO
    TITLE "Overture"
    PERFORMER "Back To The Future"
    INDEX 00 00:00:00
    INDEX 01 00:00:00
  TRACK 07 AUDIO
    TITLE "The Wallflower (Dance With Me Henry)"
    PERFORMER "Etta James"
    INDEX 00 08:19:00
    INDEX 01 08:19:00
  TRACK 08 AUDIO
    TITLE "Night Train"
    PERFORMER "Marvin Berry And The Starlighters"
    INDEX 00 11:03:00
    INDEX 01 11:03:00
  TRACK 09 AUDIO
    TITLE "Earth Angel (Will You Be Mine)"
    PERFORMER "Marvin Berry And The Starlighters"
    INDEX 00 13:21:00
    INDEX 01 13:21:00
  TRACK 10 AUDIO
    TITLE "Johnny B. Goode"
    PERFORMER "Marty McFly With The Starlighters"
    INDEX 00 16:23:00
    INDEX 01 16:23:00
```

When I'm trying to load this as playlist (still with the cue playlist plugin), I'm getting this error:

```
/Users/waker/mus/en/Back To The Future/Back To The Future [24,96]/Back To The Future [flac].cue: the number of TRACKS must be equal to the number of FILES..
```

**Comment by wdlkmpx** [comment]
I plan to fix that, the cue plugin was a hack that allowed me to
remove my deadbeef wrapper script. it was not that planned, it just
happened. Just like when you said 'thread safety'... and i was like
'what?'. My level is slowly increasing as i read more deadbeef code
(and about C programming).

**Comment by Alexey-Yakovenko** [comment]
Your patches are very useful and very high quality, so don't underestimate yourself :)

Anyway, please let me know if you don't have time to work on that - I could just take what you have in this PR, and finalize it.

**Comment by wdlkmpx** [comment]
I've been short of time lately, but i can certainly add a few more commits before handing over the control to you. 

To make deadbeef open that cuesheet only takes removing a few lines. But making deadbeef interpret that cuesheet correctly requires a true unification of the cue stuff.

I'll implement that..

Meanwhile you might want to help finish implementing the sdl output plugin
https://github.com/wdlkmpx/deadbeef/commit/e1cdaf70251286fc7603a239e7de0a5357f9275d

The audio API stuff is basically the same for sdl 1.2.x and 2.x. I haven't touched that code in a month... i was just copying stuff from the alsa/oss plugin and trying to make it work. deadbeef loads the sdl plugin and is able to use it, but there's no sound and is very crashy..

**Comment by wdlkmpx** [comment]
One thing i haven't figured out from the start is how to get the numsamples and samplerate for a specifc playItem.. 

Plugins call ```plt_insert_cue```, ```plt_insert_cue_from_buffer``` and ```plt_process_cue``` with the proper numsamples and samplerate, but there's some weird logic in some of them. How to retrieve this info.. ```endsample32 - startsample32```? ```samplerate = pl_find_meta_int (origin, ":SAMPLERATE", 0);```?

**Comment by Alexey-Yakovenko** [comment]
Why do you even need an SDL plugin?

regarding the samplerate question.. in some formats, the samplerate is stored in track properties, but that's not guaranteed. you can get it from the decoder after loading the file header, but sometimes it's just hardcoded, or even configured by the user in plugin settings.

**Comment by wdlkmpx** [comment]
I was thinking about trying to cross compile ddb for win32 with MinGW-w64. That's why i thought it would be handy to have a cross-platform output plugin, of course it should be disabled by default.

I think the cuesheet you provided requires some fundamental changes.

The function that opens cue files directly needs to be able to split a file into tracks as it opens audio files.. this is just not possible due to the current design or the method i've been using.. unless you have a solution for this.

So I locally created 2 new API functions: pl_item_set_numsamples() and pl_item_set_samplerate()

And made the flac plugin set those values for my tests. I was able to use the same ```plt_process_cue_track``` as the function that loads cue sheets from buffer with already opened audio files.

BUT... i ran into issues, i don't know if i can fix them or it has to do with the fact that once a file is inserted with ```plt_insert_file2```, the stuff just doesn't work.

In the decoder plugins i see:

	DB_playItem_t *it = deadbeef->pl_item_alloc_init (fname, plugin.plugin.id);
	...
	deadbeef->pl_lock ();
	{
		const char *cuesheet = deadbeef->pl_find_meta (it, "cuesheet");
		if (cuesheet) {
	...

This is getting messy, so I'm thinking about making the cue stuff more "object oriented"..

create a "cd" struct that contains generic info and a linked list of "tracks" (another struct with specific info). and a single routine to parse the cuesheet and store everything in the "cd" struct. and return that cd struct (dynamically allocated).

That way it would make it easier to read and implement what's missing..

**Comment by Alexey-Yakovenko** [comment]
> was thinking about trying to cross compile ddb for win32 with MinGW-w64. 

That's not gonna work as is. You'll need to patch *a lot*.
It might be easier to just install pulseaudio on windows while you working on a port.

Regarding your cuesheet concerns, I would have to give it more thought..
I don't think it requires fundamental changes, but it would require some new API for sure (which is not a problem).

**Comment by Alexey-Yakovenko** [comment]
Ok, one thing at a time...

> So I locally created 2 new API functions: pl_item_set_numsamples() and pl_item_set_samplerate()

This is generally not a very good idea, because some files can be played at any samplerate, and can have any duration/totalsamples (configured in the settings).. This is not a problem though, because those formats are not used with cuesheets... But I don't really understand why you'd want to do this.

> That way it would make it easier to read and implement what's missing..

This is just implementation details.. It may be useful to get cleaner code, but won't really solve any actual problems.

I'm gonna have another look at your code, and try to improve from there.

**Comment by Alexey-Yakovenko** [comment]
What I'm doing now: making a new branch from master, merge this PR there, then fix the issues I can identify, and will see how far I can get.

**Comment by Alexey-Yakovenko** [comment]
OK, now I understand better why you need the samplerate and duration.. Hit the same issue now :) Trying to find a solution.

**Comment by Alexey-Yakovenko** [comment]
I have something working. With some regressions, and some polish/cleanup needed, but in general I achieved what I wanted.

My test case is this:

* I used the CUE which I posted above: https://github.com/Alexey-Yakovenko/deadbeef/pull/1833#issuecomment-317513248
* The folder contains 2 CUE files, which are the same, except one points to 1.wav and 2.wav, while the other points to 1.flac and 2.flac
* When I load both CUE files individually -- they both work correctly, flac files found automatically even when CUE uses .wav extension.
* When I load the entire folder -- the album only loads once, no duplicates.

I'm considering this pull request obsolete now, closing.
Not merging `cue` to `master` yet, because some work is still needed -- cleaning up bogus error messages, fixing a newly introduced crash, fixing code duplication in `plt_load_cue_file` vs `plt_load_cuesheet_from_buffer`, etc.

**Comment by wdlkmpx** [comment]
Cool, thank you. I'll take a look and test the stuff in the cue branch.

**Pull request closed without merging**
