### PR TITLE
Changing design of the seekbar

### PR DESCRIPTION
**Pull request by TotalCaesar659**
Fixes https://github.com/Alexey-Yakovenko/deadbeef/issues/1533

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
Screenshot?

**Comment by kuba160** [comment]
I made a quick comparsion on my system (new vs. old)
deadbeef-seekbar
I'm using KDE with Breeze Dark theme.

**Comment by Alexey-Yakovenko** [comment]
I will need to build & run this, before making any decision about this change.

**Comment by Alexey-Yakovenko** [comment]
OK. I like the change to the thicker seekbar when active, but I don't like that it doesn't have a filler anymore. It looks incomplete and bland.

We can go with single-color scheme, but still need to come up with SOME filler, otherwise seekbar looks exactly the same when playing and not playing.

My suggestion for this:

draw blue background when active, with something like 30-50% alpha.

Another problem is that the blue filler overlaps with the border, and causes drawing artifacts because of antialiasing. They need to be drawn in reverse order, i.e. filler first, border second.

**Comment by TotalCaesar659** [comment]
Well, the old seekbar is very bad by design, it looks heterogenous. So I've tried to make it by myself. But I don't have any programming skills, so you can change it as you want and merge then.
Of course, my version looks good with light themes, but not with dark ones.

**Comment by Alexey-Yakovenko** [comment]
OK, I can finish what you started, but please give me some time -- I'm pretty busy atm.

**Comment by TotalCaesar659** [comment]
Yeah, you don't need to hurry up.

**Comment by Alexey-Yakovenko** [comment]
Please see the latest build on master, it should have what you wanted.

**Comment by TotalCaesar659** [comment]
Thank you very much, the seekbar and volumebar look awesome!

**Pull request closed without merging**
