### PR TITLE
Support webm in ffmpeg plugin.

### LINKED ISSUE #1511: [Support] Playing webm files
Sorry for putting this up here but I wasn't able to find another place to ask for support. 
The issue is Deadbeef doesn't detect *.webm audio files. I looked up in the plugins page and didn't find a related plugin. 

Thanks for any help.

PS - Foobar supports webm files.

### PR DESCRIPTION
**Pull request by xinyazhang**
This fixes #1511

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
Why webm specifically? Why not add all file extensions that ffmpeg can support?

**Comment by Alexey-Yakovenko** [comment]
(That's actually an interesting idea -- enumerate all supported file extensions, and expose them all)

**Comment by xinyazhang** [comment]
The problem is ffmpeg will support more formats in later version.
Asking ffmpeg for the format it supports is a good idea.
Maybe I can look into this.

**Comment by xinyazhang** [comment]
Closed since we have a better way to do this.

**Pull request closed without merging**
